// Bundles the visible effect recipes into a single standalone JS file so the
// demo gallery works both on GitHub Pages and when index.html is opened via file://.
// Run: node demo/build-data.mjs
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

const catalog = JSON.parse(readFileSync(join(root, "assets/catalog.json"), "utf8"));
const visible = catalog.visible_ids;

// Pull only the fields the gallery renderer needs, keeping the payload small.
function pick(id) {
  const j = JSON.parse(readFileSync(join(root, `assets/effects/${id}.json`), "utf8"));
  const ps = j.portable_spec;
  const sc = j.showcase;
  return {
    id: j.id,
    display_name: ps.display_name,
    description: ps.description,
    inspiration: ps.inspiration,
    target: ps.target,
    enter: ps.enter,
    exit: ps.exit,
    samples: sc.content.samples || (sc.content.sample ? [sc.content.sample] : ["Animate text"]),
    runtime: sc.runtime,
    playback: sc.playback,
    timing: sc.timing,
    rendering_contract: sc.rendering_contract,
    renderer: { id: sc.renderer.id, params: sc.renderer.params },
  };
}

const data = visible.map(pick);
const out = `// AUTO-GENERATED by demo/build-data.mjs — do not edit by hand.
window.ANIMATE_TEXT_EFFECTS = ${JSON.stringify(data, null, 2)};
`;
writeFileSync(join(here, "effects-data.js"), out);
console.log(`Wrote effects-data.js with ${data.length} effects.`);
