// AUTO-GENERATED by demo/build-data.mjs — do not edit by hand.
window.ANIMATE_TEXT_EFFECTS = [
  {
    "id": "soft-blur-in",
    "display_name": "Soft Blur",
    "description": "Per-character fade-in with a gentle blur and upward motion. Apple's signature hero-title reveal.",
    "inspiration": "Apple keynote intros; iPhone, Mac, and Vision Pro product page headlines; macOS system UI reveals.",
    "target": "per-character",
    "enter": {
      "duration_ms": 900,
      "stagger_ms": 25,
      "easing": "cubic-bezier(0.22, 1, 0.36, 1)",
      "from": {
        "opacity": 0,
        "y_px": 16,
        "blur_px": 12
      },
      "to": {
        "opacity": 1,
        "y_px": 0,
        "blur_px": 0
      }
    },
    "exit": {
      "duration_ms": 600,
      "stagger_ms": 15,
      "easing": "cubic-bezier(0.64, 0, 0.78, 0)",
      "from": {
        "opacity": 1,
        "y_px": 0,
        "blur_px": 0
      },
      "to": {
        "opacity": 0,
        "y_px": -16,
        "blur_px": 12
      }
    },
    "samples": [
      "Think different.",
      "Built to flow.",
      "Motion with intent."
    ],
    "runtime": {
      "preset": "website-default",
      "speed_multiplier": 0.72,
      "hold_ms": 550,
      "gap_ms": 320,
      "y_travel_multiplier": 0.58,
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      }
    },
    "playback": {
      "kind": "loop",
      "cycle": [
        "enter",
        "hold",
        "exit",
        "micro-delay",
        "gap"
      ],
      "replacement_behavior": "exit-before-enter",
      "hold_ms": 550,
      "micro_delay_ms": 0,
      "gap_ms": 320
    },
    "timing": {
      "enter": {
        "source_duration_ms": 900,
        "source_stagger_ms": 25,
        "scaled_duration_ms": 648,
        "scaled_stagger_ms": 18,
        "easing": "cubic-bezier(0.22, 1, 0.36, 1)"
      },
      "exit": {
        "source_duration_ms": 600,
        "source_stagger_ms": 15,
        "scaled_duration_ms": 432,
        "scaled_stagger_ms": 11,
        "easing": "cubic-bezier(0.64, 0, 0.78, 0)"
      },
      "total_formulas": {
        "enter_total_ms": "enter.scaled_duration_ms + max(0, animated_unit_count - 1) * enter.scaled_stagger_ms",
        "exit_total_ms": "exit.scaled_duration_ms + max(0, animated_unit_count - 1) * exit.scaled_stagger_ms"
      }
    },
    "rendering_contract": {
      "renderer": "generic-stagger",
      "target": "per-character",
      "stagger_mode": "normal",
      "y_travel_multiplier": 0.58,
      "transform_order": "translate3d(x_px, y_px * y_travel_multiplier, z_px) rotateX(rotate_x_deg) rotateY(rotate_y_deg) rotate(rotate_deg) scale(scale)",
      "fill_behavior": "retain final frame after each phase",
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      },
      "content_replacement": "current phrase is cleared and replaced only after exit_total_ms + micro_delay_ms"
    },
    "renderer": {
      "id": "generic-stagger",
      "params": {}
    }
  },
  {
    "id": "per-character-rise",
    "display_name": "Per-Character Rise",
    "description": "Letters slide up from below with no blur — crisp, deliberate, kinetic. Apple's clean tvOS-style reveal.",
    "inspiration": "Apple tvOS, Fitness+ intros, iPadOS home screen title appearances.",
    "target": "per-character",
    "enter": {
      "duration_ms": 700,
      "stagger_ms": 24,
      "easing": "cubic-bezier(0.2, 0.8, 0.2, 1)",
      "from": {
        "opacity": 0,
        "y_px": 32
      },
      "to": {
        "opacity": 1,
        "y_px": 0
      }
    },
    "exit": {
      "duration_ms": 420,
      "stagger_ms": 14,
      "easing": "cubic-bezier(0.7, 0, 0.84, 0)",
      "from": {
        "opacity": 1,
        "y_px": 0
      },
      "to": {
        "opacity": 0,
        "y_px": -24
      }
    },
    "samples": [
      "One more thing.",
      "Fast and fluid.",
      "Sharp by design."
    ],
    "runtime": {
      "preset": "website-default",
      "speed_multiplier": 0.72,
      "hold_ms": 550,
      "gap_ms": 320,
      "y_travel_multiplier": 0.58,
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      }
    },
    "playback": {
      "kind": "loop",
      "cycle": [
        "enter",
        "hold",
        "exit",
        "micro-delay",
        "gap"
      ],
      "replacement_behavior": "exit-before-enter",
      "hold_ms": 550,
      "micro_delay_ms": 0,
      "gap_ms": 320
    },
    "timing": {
      "enter": {
        "source_duration_ms": 700,
        "source_stagger_ms": 24,
        "scaled_duration_ms": 504,
        "scaled_stagger_ms": 17,
        "easing": "cubic-bezier(0.2, 0.8, 0.2, 1)"
      },
      "exit": {
        "source_duration_ms": 420,
        "source_stagger_ms": 14,
        "scaled_duration_ms": 302,
        "scaled_stagger_ms": 10,
        "easing": "cubic-bezier(0.7, 0, 0.84, 0)"
      },
      "total_formulas": {
        "enter_total_ms": "enter.scaled_duration_ms + max(0, animated_unit_count - 1) * enter.scaled_stagger_ms",
        "exit_total_ms": "exit.scaled_duration_ms + max(0, animated_unit_count - 1) * exit.scaled_stagger_ms"
      }
    },
    "rendering_contract": {
      "renderer": "generic-stagger",
      "target": "per-character",
      "stagger_mode": "normal",
      "y_travel_multiplier": 0.58,
      "transform_order": "translate3d(x_px, y_px * y_travel_multiplier, z_px) rotateX(rotate_x_deg) rotateY(rotate_y_deg) rotate(rotate_deg) scale(scale)",
      "fill_behavior": "retain final frame after each phase",
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      },
      "content_replacement": "current phrase is cleared and replaced only after exit_total_ms + micro_delay_ms"
    },
    "renderer": {
      "id": "generic-stagger",
      "params": {}
    }
  },
  {
    "id": "per-word-crossfade",
    "display_name": "Per-Word Crossfade",
    "description": "Words gently fade into place one after another, with a short vertical drift for a calm keynote rhythm.",
    "inspiration": "Apple product announcements and section title transitions where words are readable but still alive.",
    "target": "per-word",
    "enter": {
      "duration_ms": 700,
      "stagger_ms": 70,
      "easing": "cubic-bezier(0.16, 1, 0.3, 1)",
      "from": {
        "opacity": 0,
        "y_px": 8
      },
      "to": {
        "opacity": 1,
        "y_px": 0
      }
    },
    "exit": {
      "duration_ms": 500,
      "stagger_ms": 40,
      "easing": "cubic-bezier(0.7, 0, 0.84, 0)",
      "from": {
        "opacity": 1,
        "y_px": 0
      },
      "to": {
        "opacity": 0,
        "y_px": -6
      }
    },
    "samples": [
      "Beautifully simple.",
      "Designed for focus.",
      "Built for people."
    ],
    "runtime": {
      "preset": "website-default",
      "speed_multiplier": 0.72,
      "hold_ms": 550,
      "gap_ms": 320,
      "y_travel_multiplier": 0.58,
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      }
    },
    "playback": {
      "kind": "loop",
      "cycle": [
        "enter",
        "hold",
        "exit",
        "micro-delay",
        "gap"
      ],
      "replacement_behavior": "exit-before-enter",
      "hold_ms": 550,
      "micro_delay_ms": 70,
      "gap_ms": 320
    },
    "timing": {
      "enter": {
        "source_duration_ms": 700,
        "source_stagger_ms": 70,
        "scaled_duration_ms": 504,
        "scaled_stagger_ms": 50,
        "easing": "cubic-bezier(0.16, 1, 0.3, 1)"
      },
      "exit": {
        "source_duration_ms": 500,
        "source_stagger_ms": 40,
        "scaled_duration_ms": 360,
        "scaled_stagger_ms": 29,
        "easing": "cubic-bezier(0.7, 0, 0.84, 0)"
      },
      "total_formulas": {
        "enter_total_ms": "enter.scaled_duration_ms + max(0, animated_unit_count - 1) * enter.scaled_stagger_ms",
        "exit_total_ms": "exit.scaled_duration_ms + max(0, animated_unit_count - 1) * exit.scaled_stagger_ms"
      }
    },
    "rendering_contract": {
      "renderer": "generic-stagger",
      "target": "per-word",
      "stagger_mode": "normal",
      "y_travel_multiplier": 0.58,
      "transform_order": "translate3d(x_px, y_px * y_travel_multiplier, z_px) rotateX(rotate_x_deg) rotateY(rotate_y_deg) rotate(rotate_deg) scale(scale)",
      "fill_behavior": "retain final frame after each phase",
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      },
      "content_replacement": "current phrase is cleared and replaced only after exit_total_ms + micro_delay_ms"
    },
    "renderer": {
      "id": "generic-stagger",
      "params": {}
    }
  },
  {
    "id": "spring-scale-in",
    "display_name": "Spring Scale In",
    "description": "Words pop in with a soft overshoot scale, like a physical spring settling into place.",
    "inspiration": "iOS app icons bouncing into the home screen, macOS Dock, widget appearances, Vision Pro floating UI pops.",
    "target": "per-word",
    "enter": {
      "duration_ms": 360,
      "stagger_ms": 95,
      "easing": "cubic-bezier(0.34, 1.56, 0.64, 1)",
      "from": {
        "opacity": 0,
        "scale": 0.7
      },
      "to": {
        "opacity": 1,
        "scale": 1
      }
    },
    "exit": {
      "duration_ms": 200,
      "stagger_ms": 80,
      "easing": "cubic-bezier(0.7, 0, 0.84, 0)",
      "from": {
        "opacity": 1,
        "scale": 1
      },
      "to": {
        "opacity": 0,
        "scale": 0.8
      }
    },
    "samples": [
      "Fast. Crisp. Fluid.",
      "Pop into place.",
      "Smooth by default."
    ],
    "runtime": {
      "preset": "website-default",
      "speed_multiplier": 0.72,
      "hold_ms": 550,
      "gap_ms": 320,
      "y_travel_multiplier": 0.58,
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      }
    },
    "playback": {
      "kind": "loop",
      "cycle": [
        "enter",
        "hold",
        "exit",
        "micro-delay",
        "gap"
      ],
      "replacement_behavior": "exit-before-enter",
      "hold_ms": 550,
      "micro_delay_ms": 35,
      "gap_ms": 320
    },
    "timing": {
      "enter": {
        "source_duration_ms": 360,
        "source_stagger_ms": 95,
        "scaled_duration_ms": 259,
        "scaled_stagger_ms": 68,
        "easing": "cubic-bezier(0.34, 1.56, 0.64, 1)"
      },
      "exit": {
        "source_duration_ms": 200,
        "source_stagger_ms": 80,
        "scaled_duration_ms": 144,
        "scaled_stagger_ms": 58,
        "easing": "cubic-bezier(0.7, 0, 0.84, 0)"
      },
      "total_formulas": {
        "enter_total_ms": "enter.scaled_duration_ms + max(0, animated_unit_count - 1) * enter.scaled_stagger_ms",
        "exit_total_ms": "exit.scaled_duration_ms + max(0, animated_unit_count - 1) * exit.scaled_stagger_ms"
      }
    },
    "rendering_contract": {
      "renderer": "generic-stagger",
      "target": "per-word",
      "stagger_mode": "normal",
      "y_travel_multiplier": 0.58,
      "transform_order": "translate3d(x_px, y_px * y_travel_multiplier, z_px) rotateX(rotate_x_deg) rotateY(rotate_y_deg) rotate(rotate_deg) scale(scale)",
      "fill_behavior": "retain final frame after each phase",
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      },
      "content_replacement": "current phrase is cleared and replaced only after exit_total_ms + micro_delay_ms"
    },
    "renderer": {
      "id": "generic-stagger",
      "params": {}
    }
  },
  {
    "id": "mask-reveal-up",
    "display_name": "Mask Reveal Up",
    "description": "Lines reveal upward with a soft masked feel and compact stagger.",
    "inspiration": "Apple section transitions where multiline copy rises in with control.",
    "target": "per-line",
    "enter": {
      "duration_ms": 760,
      "stagger_ms": 90,
      "easing": "cubic-bezier(0.22, 1, 0.36, 1)",
      "from": {
        "opacity": 0,
        "y_px": 30,
        "blur_px": 6
      },
      "to": {
        "opacity": 1,
        "y_px": 0,
        "blur_px": 0
      }
    },
    "exit": {
      "duration_ms": 520,
      "stagger_ms": 70,
      "easing": "cubic-bezier(0.64, 0, 0.78, 0)",
      "from": {
        "opacity": 1,
        "y_px": 0,
        "blur_px": 0
      },
      "to": {
        "opacity": 0,
        "y_px": -22,
        "blur_px": 6
      }
    },
    "samples": [
      "Designed to move.\nBuilt to focus.",
      "Quiet motion.\nStrong hierarchy.",
      "Premium feel.\nEvery frame."
    ],
    "runtime": {
      "preset": "website-default",
      "speed_multiplier": 0.72,
      "hold_ms": 550,
      "gap_ms": 320,
      "y_travel_multiplier": 0.58,
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      }
    },
    "playback": {
      "kind": "loop",
      "cycle": [
        "enter",
        "hold",
        "exit",
        "micro-delay",
        "gap"
      ],
      "replacement_behavior": "exit-before-enter",
      "hold_ms": 550,
      "micro_delay_ms": 35,
      "gap_ms": 320
    },
    "timing": {
      "enter": {
        "source_duration_ms": 760,
        "source_stagger_ms": 90,
        "scaled_duration_ms": 547,
        "scaled_stagger_ms": 65,
        "easing": "cubic-bezier(0.22, 1, 0.36, 1)"
      },
      "exit": {
        "source_duration_ms": 520,
        "source_stagger_ms": 70,
        "scaled_duration_ms": 374,
        "scaled_stagger_ms": 50,
        "easing": "cubic-bezier(0.64, 0, 0.78, 0)"
      },
      "total_formulas": {
        "enter_total_ms": "enter.scaled_duration_ms + max(0, animated_unit_count - 1) * enter.scaled_stagger_ms",
        "exit_total_ms": "exit.scaled_duration_ms + max(0, animated_unit_count - 1) * exit.scaled_stagger_ms"
      }
    },
    "rendering_contract": {
      "renderer": "generic-stagger",
      "target": "per-line",
      "stagger_mode": "normal",
      "y_travel_multiplier": 0.58,
      "transform_order": "translate3d(x_px, y_px * y_travel_multiplier, z_px) rotateX(rotate_x_deg) rotateY(rotate_y_deg) rotate(rotate_deg) scale(scale)",
      "fill_behavior": "retain final frame after each phase",
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      },
      "content_replacement": "current phrase is cleared and replaced only after exit_total_ms + micro_delay_ms"
    },
    "renderer": {
      "id": "generic-stagger",
      "params": {}
    }
  },
  {
    "id": "line-by-line-slide",
    "display_name": "Line-by-Line Slide",
    "description": "Each line enters from the left with a staggered slide and exits to the right for a flowing paragraph reveal.",
    "inspiration": "Apple landing page subheads and section headers that breathe line by line.",
    "target": "per-line",
    "enter": {
      "duration_ms": 900,
      "stagger_ms": 120,
      "easing": "cubic-bezier(0.22, 1, 0.36, 1)",
      "from": {
        "opacity": 0,
        "x_px": -48
      },
      "to": {
        "opacity": 1,
        "x_px": 0
      }
    },
    "exit": {
      "duration_ms": 600,
      "stagger_ms": 80,
      "easing": "cubic-bezier(0.64, 0, 0.78, 0)",
      "from": {
        "opacity": 1,
        "x_px": 0
      },
      "to": {
        "opacity": 0,
        "x_px": 48
      }
    },
    "samples": [
      "Think different.\nDo more.",
      "Built for speed.\nMade to last.",
      "Clear ideas.\nClean motion."
    ],
    "runtime": {
      "preset": "website-default",
      "speed_multiplier": 0.72,
      "hold_ms": 550,
      "gap_ms": 320,
      "y_travel_multiplier": 0.58,
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      }
    },
    "playback": {
      "kind": "loop",
      "cycle": [
        "enter",
        "hold",
        "exit",
        "micro-delay",
        "gap"
      ],
      "replacement_behavior": "exit-before-enter",
      "hold_ms": 550,
      "micro_delay_ms": 20,
      "gap_ms": 320
    },
    "timing": {
      "enter": {
        "source_duration_ms": 900,
        "source_stagger_ms": 120,
        "scaled_duration_ms": 648,
        "scaled_stagger_ms": 86,
        "easing": "cubic-bezier(0.22, 1, 0.36, 1)"
      },
      "exit": {
        "source_duration_ms": 600,
        "source_stagger_ms": 80,
        "scaled_duration_ms": 432,
        "scaled_stagger_ms": 58,
        "easing": "cubic-bezier(0.64, 0, 0.78, 0)"
      },
      "total_formulas": {
        "enter_total_ms": "enter.scaled_duration_ms + max(0, animated_unit_count - 1) * enter.scaled_stagger_ms",
        "exit_total_ms": "exit.scaled_duration_ms + max(0, animated_unit_count - 1) * exit.scaled_stagger_ms"
      }
    },
    "rendering_contract": {
      "renderer": "generic-stagger",
      "target": "per-line",
      "stagger_mode": "normal",
      "y_travel_multiplier": 0.58,
      "transform_order": "translate3d(x_px, y_px * y_travel_multiplier, z_px) rotateX(rotate_x_deg) rotateY(rotate_y_deg) rotate(rotate_deg) scale(scale)",
      "fill_behavior": "retain final frame after each phase",
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      },
      "content_replacement": "current phrase is cleared and replaced only after exit_total_ms + micro_delay_ms"
    },
    "renderer": {
      "id": "generic-stagger",
      "params": {}
    }
  },
  {
    "id": "typewriter",
    "display_name": "Typewriter",
    "description": "Per-character stepped reveal with a minimal editorial typing rhythm.",
    "inspiration": "System-like text build patterns in Apple presentation and utility UI.",
    "target": "per-character",
    "enter": {
      "duration_ms": 240,
      "stagger_ms": 46,
      "easing": "steps(1, end)",
      "from": {
        "opacity": 0,
        "y_px": 0
      },
      "to": {
        "opacity": 1,
        "y_px": 0
      }
    },
    "exit": {
      "duration_ms": 260,
      "stagger_ms": 10,
      "easing": "cubic-bezier(0.7, 0, 0.84, 0)",
      "from": {
        "opacity": 1,
        "y_px": 0
      },
      "to": {
        "opacity": 0,
        "y_px": -4
      }
    },
    "samples": [
      "Precision in motion.",
      "Write. Pause. Continue."
    ],
    "runtime": {
      "preset": "website-default",
      "speed_multiplier": 0.72,
      "hold_ms": 550,
      "gap_ms": 320,
      "y_travel_multiplier": 0.58,
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      }
    },
    "playback": {
      "kind": "loop",
      "cycle": [
        "enter",
        "hold",
        "exit",
        "micro-delay",
        "gap"
      ],
      "replacement_behavior": "exit-before-enter",
      "hold_ms": 550,
      "micro_delay_ms": 85,
      "gap_ms": 320
    },
    "timing": {
      "enter": {
        "source_duration_ms": 240,
        "source_stagger_ms": 46,
        "scaled_duration_ms": 173,
        "scaled_stagger_ms": 33,
        "easing": "steps(1, end)"
      },
      "exit": {
        "source_duration_ms": 260,
        "source_stagger_ms": 10,
        "scaled_duration_ms": 187,
        "scaled_stagger_ms": 7,
        "easing": "cubic-bezier(0.7, 0, 0.84, 0)"
      },
      "total_formulas": {
        "enter_total_ms": "enter.scaled_duration_ms + max(0, animated_unit_count - 1) * enter.scaled_stagger_ms",
        "exit_total_ms": "exit.scaled_duration_ms + max(0, animated_unit_count - 1) * exit.scaled_stagger_ms"
      }
    },
    "rendering_contract": {
      "renderer": "generic-stagger",
      "target": "per-character",
      "stagger_mode": "normal",
      "y_travel_multiplier": 0.58,
      "transform_order": "translate3d(x_px, y_px * y_travel_multiplier, z_px) rotateX(rotate_x_deg) rotateY(rotate_y_deg) rotate(rotate_deg) scale(scale)",
      "fill_behavior": "retain final frame after each phase",
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      },
      "content_replacement": "current phrase is cleared and replaced only after exit_total_ms + micro_delay_ms"
    },
    "renderer": {
      "id": "generic-stagger",
      "params": {}
    }
  },
  {
    "id": "micro-scale-fade",
    "display_name": "Micro Scale Fade",
    "description": "A calm, tiny scale pop used as subtle premium polish for labels and headings.",
    "inspiration": "Apple system status copy, secondary UI labels, and lightweight onboarding micro-animations.",
    "target": "whole",
    "enter": {
      "duration_ms": 600,
      "stagger_ms": 0,
      "easing": "cubic-bezier(0.32, 0.72, 0, 1)",
      "from": {
        "opacity": 0,
        "scale": 0.96
      },
      "to": {
        "opacity": 1,
        "scale": 1
      }
    },
    "exit": {
      "duration_ms": 400,
      "stagger_ms": 0,
      "easing": "cubic-bezier(0.7, 0, 0.84, 0)",
      "from": {
        "opacity": 1,
        "scale": 1
      },
      "to": {
        "opacity": 0,
        "scale": 0.96
      }
    },
    "samples": [
      "Welcome to motion.",
      "Small details matter.",
      "Quietly premium."
    ],
    "runtime": {
      "preset": "website-default",
      "speed_multiplier": 0.72,
      "hold_ms": 550,
      "gap_ms": 320,
      "y_travel_multiplier": 0.58,
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      }
    },
    "playback": {
      "kind": "loop",
      "cycle": [
        "enter",
        "hold",
        "exit",
        "micro-delay",
        "gap"
      ],
      "replacement_behavior": "exit-before-enter",
      "hold_ms": 550,
      "micro_delay_ms": 20,
      "gap_ms": 320
    },
    "timing": {
      "enter": {
        "source_duration_ms": 600,
        "source_stagger_ms": 0,
        "scaled_duration_ms": 432,
        "scaled_stagger_ms": 0,
        "easing": "cubic-bezier(0.32, 0.72, 0, 1)"
      },
      "exit": {
        "source_duration_ms": 400,
        "source_stagger_ms": 0,
        "scaled_duration_ms": 288,
        "scaled_stagger_ms": 0,
        "easing": "cubic-bezier(0.7, 0, 0.84, 0)"
      },
      "total_formulas": {
        "enter_total_ms": "enter.scaled_duration_ms + max(0, animated_unit_count - 1) * enter.scaled_stagger_ms",
        "exit_total_ms": "exit.scaled_duration_ms + max(0, animated_unit_count - 1) * exit.scaled_stagger_ms"
      }
    },
    "rendering_contract": {
      "renderer": "generic-stagger",
      "target": "whole",
      "stagger_mode": "normal",
      "y_travel_multiplier": 0.58,
      "transform_order": "translate3d(x_px, y_px * y_travel_multiplier, z_px) rotateX(rotate_x_deg) rotateY(rotate_y_deg) rotate(rotate_deg) scale(scale)",
      "fill_behavior": "retain final frame after each phase",
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      },
      "content_replacement": "current phrase is cleared and replaced only after exit_total_ms + micro_delay_ms"
    },
    "renderer": {
      "id": "generic-stagger",
      "params": {}
    }
  },
  {
    "id": "shimmer-sweep",
    "display_name": "Shimmer Sweep",
    "description": "A subtle sweep across a clean headline, blending in while gliding from left to center.",
    "inspiration": "Premium hero copy transitions where a short soft push is used before settle.",
    "target": "whole",
    "enter": {
      "duration_ms": 850,
      "stagger_ms": 0,
      "easing": "cubic-bezier(0.22, 1, 0.36, 1)",
      "from": {
        "opacity": 0,
        "x_px": -22,
        "blur_px": 8
      },
      "to": {
        "opacity": 1,
        "x_px": 0,
        "blur_px": 0
      }
    },
    "exit": {
      "duration_ms": 650,
      "stagger_ms": 0,
      "easing": "cubic-bezier(0.7, 0, 0.84, 0)",
      "from": {
        "opacity": 1,
        "x_px": 0,
        "blur_px": 0
      },
      "to": {
        "opacity": 0,
        "x_px": 22,
        "blur_px": 8
      }
    },
    "samples": [
      "Shiny details.",
      "Glide with intent.",
      "Soft and precise."
    ],
    "runtime": {
      "preset": "website-default",
      "speed_multiplier": 0.72,
      "hold_ms": 550,
      "gap_ms": 320,
      "y_travel_multiplier": 0.58,
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      }
    },
    "playback": {
      "kind": "loop",
      "cycle": [
        "enter",
        "hold",
        "exit",
        "micro-delay",
        "gap"
      ],
      "replacement_behavior": "exit-before-enter",
      "hold_ms": 550,
      "micro_delay_ms": 36,
      "gap_ms": 320
    },
    "timing": {
      "enter": {
        "source_duration_ms": 850,
        "source_stagger_ms": 0,
        "scaled_duration_ms": 612,
        "scaled_stagger_ms": 0,
        "easing": "cubic-bezier(0.22, 1, 0.36, 1)"
      },
      "exit": {
        "source_duration_ms": 650,
        "source_stagger_ms": 0,
        "scaled_duration_ms": 468,
        "scaled_stagger_ms": 0,
        "easing": "cubic-bezier(0.7, 0, 0.84, 0)"
      },
      "total_formulas": {
        "enter_total_ms": "enter.scaled_duration_ms + max(0, animated_unit_count - 1) * enter.scaled_stagger_ms",
        "exit_total_ms": "exit.scaled_duration_ms + max(0, animated_unit_count - 1) * exit.scaled_stagger_ms"
      }
    },
    "rendering_contract": {
      "renderer": "generic-stagger",
      "target": "whole",
      "stagger_mode": "normal",
      "y_travel_multiplier": 0.58,
      "transform_order": "translate3d(x_px, y_px * y_travel_multiplier, z_px) rotateX(rotate_x_deg) rotateY(rotate_y_deg) rotate(rotate_deg) scale(scale)",
      "fill_behavior": "retain final frame after each phase",
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      },
      "content_replacement": "current phrase is cleared and replaced only after exit_total_ms + micro_delay_ms"
    },
    "renderer": {
      "id": "generic-stagger",
      "params": {}
    }
  },
  {
    "id": "fade-through",
    "display_name": "Fade Through",
    "description": "A Material-style content transition: old fades out, new fades in with a soft delay.",
    "inspiration": "Google Material fade through transitions for same-level UI changes.",
    "target": "whole",
    "enter": {
      "duration_ms": 420,
      "stagger_ms": 0,
      "easing": "cubic-bezier(0.2, 0, 0, 1)",
      "from": {
        "opacity": 0,
        "y_px": 6,
        "scale": 0.99,
        "blur_px": 2
      },
      "to": {
        "opacity": 1,
        "y_px": 0,
        "scale": 1,
        "blur_px": 0
      }
    },
    "exit": {
      "duration_ms": 260,
      "stagger_ms": 0,
      "easing": "cubic-bezier(0.4, 0, 1, 1)",
      "from": {
        "opacity": 1,
        "y_px": 0,
        "scale": 1,
        "blur_px": 0
      },
      "to": {
        "opacity": 0,
        "y_px": -4,
        "scale": 1,
        "blur_px": 0
      }
    },
    "samples": [
      "Calm transitions.",
      "Fade through content.",
      "Focus shifts smoothly."
    ],
    "runtime": {
      "preset": "website-default",
      "speed_multiplier": 0.72,
      "hold_ms": 550,
      "gap_ms": 320,
      "y_travel_multiplier": 0.58,
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      }
    },
    "playback": {
      "kind": "loop",
      "cycle": [
        "enter",
        "hold",
        "exit",
        "micro-delay",
        "gap"
      ],
      "replacement_behavior": "exit-before-enter",
      "hold_ms": 550,
      "micro_delay_ms": 60,
      "gap_ms": 320
    },
    "timing": {
      "enter": {
        "source_duration_ms": 420,
        "source_stagger_ms": 0,
        "scaled_duration_ms": 302,
        "scaled_stagger_ms": 0,
        "easing": "cubic-bezier(0.2, 0, 0, 1)"
      },
      "exit": {
        "source_duration_ms": 260,
        "source_stagger_ms": 0,
        "scaled_duration_ms": 187,
        "scaled_stagger_ms": 0,
        "easing": "cubic-bezier(0.4, 0, 1, 1)"
      },
      "total_formulas": {
        "enter_total_ms": "enter.scaled_duration_ms + max(0, animated_unit_count - 1) * enter.scaled_stagger_ms",
        "exit_total_ms": "exit.scaled_duration_ms + max(0, animated_unit_count - 1) * exit.scaled_stagger_ms"
      }
    },
    "rendering_contract": {
      "renderer": "generic-stagger",
      "target": "whole",
      "stagger_mode": "normal",
      "y_travel_multiplier": 0.58,
      "transform_order": "translate3d(x_px, y_px * y_travel_multiplier, z_px) rotateX(rotate_x_deg) rotateY(rotate_y_deg) rotate(rotate_deg) scale(scale)",
      "fill_behavior": "retain final frame after each phase",
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      },
      "content_replacement": "current phrase is cleared and replaced only after exit_total_ms + micro_delay_ms"
    },
    "renderer": {
      "id": "generic-stagger",
      "params": {}
    }
  },
  {
    "id": "shared-axis-y",
    "display_name": "Word Cut Staircase",
    "description": "Per-word hard-cut transition with staircase timing for sharp editorial swaps.",
    "inspiration": "Hard-cut typography timing with stepped word sequencing.",
    "target": "per-word",
    "enter": {
      "duration_ms": 180,
      "stagger_ms": 78,
      "easing": "steps(1, end)",
      "from": {
        "opacity": 0,
        "y_px": 0,
        "scale": 1
      },
      "to": {
        "opacity": 1,
        "y_px": 0,
        "scale": 1
      }
    },
    "exit": {
      "duration_ms": 140,
      "stagger_ms": 78,
      "easing": "steps(1, end)",
      "from": {
        "opacity": 1,
        "y_px": 0,
        "scale": 1
      },
      "to": {
        "opacity": 0,
        "y_px": 0,
        "scale": 1
      }
    },
    "samples": [
      "Layered navigation.",
      "Hierarchy made clear.",
      "Depth with restraint."
    ],
    "runtime": {
      "preset": "website-default",
      "speed_multiplier": 0.72,
      "hold_ms": 550,
      "gap_ms": 320,
      "y_travel_multiplier": 0.58,
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      }
    },
    "playback": {
      "kind": "loop",
      "cycle": [
        "enter",
        "hold",
        "exit",
        "micro-delay",
        "gap"
      ],
      "replacement_behavior": "exit-before-enter",
      "hold_ms": 550,
      "micro_delay_ms": 28,
      "gap_ms": 320
    },
    "timing": {
      "enter": {
        "source_duration_ms": 180,
        "source_stagger_ms": 78,
        "scaled_duration_ms": 140,
        "scaled_stagger_ms": 56,
        "easing": "steps(1, end)"
      },
      "exit": {
        "source_duration_ms": 140,
        "source_stagger_ms": 78,
        "scaled_duration_ms": 140,
        "scaled_stagger_ms": 56,
        "easing": "steps(1, end)"
      },
      "total_formulas": {
        "enter_total_ms": "enter.scaled_duration_ms + max(0, animated_unit_count - 1) * enter.scaled_stagger_ms",
        "exit_total_ms": "exit.scaled_duration_ms + max(0, animated_unit_count - 1) * exit.scaled_stagger_ms"
      }
    },
    "rendering_contract": {
      "renderer": "generic-stagger",
      "target": "per-word",
      "stagger_mode": "normal",
      "y_travel_multiplier": 0.58,
      "transform_order": "translate3d(x_px, y_px * y_travel_multiplier, z_px) rotateX(rotate_x_deg) rotateY(rotate_y_deg) rotate(rotate_deg) scale(scale)",
      "fill_behavior": "retain final frame after each phase",
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      },
      "content_replacement": "current phrase is cleared and replaced only after exit_total_ms + micro_delay_ms"
    },
    "renderer": {
      "id": "generic-stagger",
      "params": {}
    }
  },
  {
    "id": "shared-axis-z",
    "display_name": "Shared Axis Z",
    "description": "Scale-based shared-axis transition for focus shifts and context depth.",
    "inspiration": "Google Material shared axis (Z), adapted for typography swaps.",
    "target": "whole",
    "enter": {
      "duration_ms": 520,
      "stagger_ms": 0,
      "easing": "cubic-bezier(0.2, 0, 0, 1)",
      "from": {
        "opacity": 0,
        "scale": 0.9,
        "blur_px": 2
      },
      "to": {
        "opacity": 1,
        "scale": 1,
        "blur_px": 0
      }
    },
    "exit": {
      "duration_ms": 360,
      "stagger_ms": 0,
      "easing": "cubic-bezier(0.4, 0, 1, 1)",
      "from": {
        "opacity": 1,
        "scale": 1,
        "blur_px": 0
      },
      "to": {
        "opacity": 0,
        "scale": 1.06,
        "blur_px": 1
      }
    },
    "samples": [
      "Zooming between states.",
      "Elevate and settle.",
      "Scale with purpose."
    ],
    "runtime": {
      "preset": "website-default",
      "speed_multiplier": 0.72,
      "hold_ms": 550,
      "gap_ms": 320,
      "y_travel_multiplier": 0.58,
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      }
    },
    "playback": {
      "kind": "loop",
      "cycle": [
        "enter",
        "hold",
        "exit",
        "micro-delay",
        "gap"
      ],
      "replacement_behavior": "exit-before-enter",
      "hold_ms": 550,
      "micro_delay_ms": 20,
      "gap_ms": 320
    },
    "timing": {
      "enter": {
        "source_duration_ms": 520,
        "source_stagger_ms": 0,
        "scaled_duration_ms": 374,
        "scaled_stagger_ms": 0,
        "easing": "cubic-bezier(0.2, 0, 0, 1)"
      },
      "exit": {
        "source_duration_ms": 360,
        "source_stagger_ms": 0,
        "scaled_duration_ms": 259,
        "scaled_stagger_ms": 0,
        "easing": "cubic-bezier(0.4, 0, 1, 1)"
      },
      "total_formulas": {
        "enter_total_ms": "enter.scaled_duration_ms + max(0, animated_unit_count - 1) * enter.scaled_stagger_ms",
        "exit_total_ms": "exit.scaled_duration_ms + max(0, animated_unit_count - 1) * exit.scaled_stagger_ms"
      }
    },
    "rendering_contract": {
      "renderer": "generic-stagger",
      "target": "whole",
      "stagger_mode": "normal",
      "y_travel_multiplier": 0.58,
      "transform_order": "translate3d(x_px, y_px * y_travel_multiplier, z_px) rotateX(rotate_x_deg) rotateY(rotate_y_deg) rotate(rotate_deg) scale(scale)",
      "fill_behavior": "retain final frame after each phase",
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      },
      "content_replacement": "current phrase is cleared and replaced only after exit_total_ms + micro_delay_ms"
    },
    "renderer": {
      "id": "generic-stagger",
      "params": {}
    }
  },
  {
    "id": "blur-out-up",
    "display_name": "Blur Out Up",
    "description": "Words arrive clean and depart upward with increasing blur for airy exits.",
    "inspiration": "Apple-style light typography where exit has more character than entry.",
    "target": "per-word",
    "enter": {
      "duration_ms": 560,
      "stagger_ms": 28,
      "easing": "cubic-bezier(0.22, 1, 0.36, 1)",
      "from": {
        "opacity": 0,
        "y_px": 10,
        "blur_px": 6
      },
      "to": {
        "opacity": 1,
        "y_px": 0,
        "blur_px": 0
      }
    },
    "exit": {
      "duration_ms": 480,
      "stagger_ms": 24,
      "easing": "cubic-bezier(0.64, 0, 0.78, 0)",
      "from": {
        "opacity": 1,
        "y_px": 0,
        "blur_px": 0
      },
      "to": {
        "opacity": 0,
        "y_px": -14,
        "blur_px": 8
      }
    },
    "samples": [
      "Clear in, airy out.",
      "Lightweight typography.",
      "Exit with grace."
    ],
    "runtime": {
      "preset": "website-default",
      "speed_multiplier": 0.72,
      "hold_ms": 550,
      "gap_ms": 320,
      "y_travel_multiplier": 0.58,
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      }
    },
    "playback": {
      "kind": "loop",
      "cycle": [
        "enter",
        "hold",
        "exit",
        "micro-delay",
        "gap"
      ],
      "replacement_behavior": "exit-before-enter",
      "hold_ms": 550,
      "micro_delay_ms": 35,
      "gap_ms": 320
    },
    "timing": {
      "enter": {
        "source_duration_ms": 560,
        "source_stagger_ms": 28,
        "scaled_duration_ms": 403,
        "scaled_stagger_ms": 20,
        "easing": "cubic-bezier(0.22, 1, 0.36, 1)"
      },
      "exit": {
        "source_duration_ms": 480,
        "source_stagger_ms": 24,
        "scaled_duration_ms": 346,
        "scaled_stagger_ms": 17,
        "easing": "cubic-bezier(0.64, 0, 0.78, 0)"
      },
      "total_formulas": {
        "enter_total_ms": "enter.scaled_duration_ms + max(0, animated_unit_count - 1) * enter.scaled_stagger_ms",
        "exit_total_ms": "exit.scaled_duration_ms + max(0, animated_unit_count - 1) * exit.scaled_stagger_ms"
      }
    },
    "rendering_contract": {
      "renderer": "generic-stagger",
      "target": "per-word",
      "stagger_mode": "normal",
      "y_travel_multiplier": 0.58,
      "transform_order": "translate3d(x_px, y_px * y_travel_multiplier, z_px) rotateX(rotate_x_deg) rotateY(rotate_y_deg) rotate(rotate_deg) scale(scale)",
      "fill_behavior": "retain final frame after each phase",
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      },
      "content_replacement": "current phrase is cleared and replaced only after exit_total_ms + micro_delay_ms"
    },
    "renderer": {
      "id": "generic-stagger",
      "params": {}
    }
  },
  {
    "id": "scale-down-fade",
    "display_name": "Scale Down Fade",
    "description": "Subtle premium settle-in with a restrained scale-down fade on exit.",
    "inspiration": "Apple product copy transitions where motion remains quiet and precise.",
    "target": "whole",
    "enter": {
      "duration_ms": 520,
      "stagger_ms": 0,
      "easing": "cubic-bezier(0.22, 1, 0.36, 1)",
      "from": {
        "opacity": 0,
        "y_px": 8,
        "scale": 1.04
      },
      "to": {
        "opacity": 1,
        "y_px": 0,
        "scale": 1
      }
    },
    "exit": {
      "duration_ms": 380,
      "stagger_ms": 0,
      "easing": "cubic-bezier(0.64, 0, 0.78, 0)",
      "from": {
        "opacity": 1,
        "y_px": 0,
        "scale": 1
      },
      "to": {
        "opacity": 0,
        "y_px": -8,
        "scale": 0.94
      }
    },
    "samples": [
      "Quietly refined.",
      "Polished transitions.",
      "A soft close."
    ],
    "runtime": {
      "preset": "website-default",
      "speed_multiplier": 0.72,
      "hold_ms": 550,
      "gap_ms": 320,
      "y_travel_multiplier": 0.58,
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      }
    },
    "playback": {
      "kind": "loop",
      "cycle": [
        "enter",
        "hold",
        "exit",
        "micro-delay",
        "gap"
      ],
      "replacement_behavior": "exit-before-enter",
      "hold_ms": 550,
      "micro_delay_ms": 20,
      "gap_ms": 320
    },
    "timing": {
      "enter": {
        "source_duration_ms": 520,
        "source_stagger_ms": 0,
        "scaled_duration_ms": 374,
        "scaled_stagger_ms": 0,
        "easing": "cubic-bezier(0.22, 1, 0.36, 1)"
      },
      "exit": {
        "source_duration_ms": 380,
        "source_stagger_ms": 0,
        "scaled_duration_ms": 274,
        "scaled_stagger_ms": 0,
        "easing": "cubic-bezier(0.64, 0, 0.78, 0)"
      },
      "total_formulas": {
        "enter_total_ms": "enter.scaled_duration_ms + max(0, animated_unit_count - 1) * enter.scaled_stagger_ms",
        "exit_total_ms": "exit.scaled_duration_ms + max(0, animated_unit_count - 1) * exit.scaled_stagger_ms"
      }
    },
    "rendering_contract": {
      "renderer": "generic-stagger",
      "target": "whole",
      "stagger_mode": "normal",
      "y_travel_multiplier": 0.58,
      "transform_order": "translate3d(x_px, y_px * y_travel_multiplier, z_px) rotateX(rotate_x_deg) rotateY(rotate_y_deg) rotate(rotate_deg) scale(scale)",
      "fill_behavior": "retain final frame after each phase",
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      },
      "content_replacement": "current phrase is cleared and replaced only after exit_total_ms + micro_delay_ms"
    },
    "renderer": {
      "id": "generic-stagger",
      "params": {}
    }
  },
  {
    "id": "focus-blur-resolve",
    "display_name": "Focus Blur Resolve",
    "description": "A premium focus pull from heavy blur to crisp text, then a soft blur-out exit.",
    "inspiration": "Apple-style hero transitions that resolve detail with cinematic restraint.",
    "target": "whole",
    "enter": {
      "duration_ms": 760,
      "stagger_ms": 0,
      "easing": "cubic-bezier(0.22, 1, 0.36, 1)",
      "from": {
        "opacity": 0,
        "y_px": 14,
        "blur_px": 14,
        "scale": 1.01
      },
      "to": {
        "opacity": 1,
        "y_px": 0,
        "blur_px": 0,
        "scale": 1
      }
    },
    "exit": {
      "duration_ms": 520,
      "stagger_ms": 0,
      "easing": "cubic-bezier(0.64, 0, 0.78, 0)",
      "from": {
        "opacity": 1,
        "y_px": 0,
        "blur_px": 0,
        "scale": 1
      },
      "to": {
        "opacity": 0,
        "y_px": -10,
        "blur_px": 10,
        "scale": 1
      }
    },
    "samples": [
      "Focus resolves clearly.",
      "Detail emerges.",
      "Then softly recedes."
    ],
    "runtime": {
      "preset": "website-default",
      "speed_multiplier": 0.72,
      "hold_ms": 550,
      "gap_ms": 320,
      "y_travel_multiplier": 0.58,
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      }
    },
    "playback": {
      "kind": "loop",
      "cycle": [
        "enter",
        "hold",
        "exit",
        "micro-delay",
        "gap"
      ],
      "replacement_behavior": "exit-before-enter",
      "hold_ms": 550,
      "micro_delay_ms": 35,
      "gap_ms": 320
    },
    "timing": {
      "enter": {
        "source_duration_ms": 760,
        "source_stagger_ms": 0,
        "scaled_duration_ms": 547,
        "scaled_stagger_ms": 0,
        "easing": "cubic-bezier(0.22, 1, 0.36, 1)"
      },
      "exit": {
        "source_duration_ms": 520,
        "source_stagger_ms": 0,
        "scaled_duration_ms": 374,
        "scaled_stagger_ms": 0,
        "easing": "cubic-bezier(0.64, 0, 0.78, 0)"
      },
      "total_formulas": {
        "enter_total_ms": "enter.scaled_duration_ms + max(0, animated_unit_count - 1) * enter.scaled_stagger_ms",
        "exit_total_ms": "exit.scaled_duration_ms + max(0, animated_unit_count - 1) * exit.scaled_stagger_ms"
      }
    },
    "rendering_contract": {
      "renderer": "generic-stagger",
      "target": "whole",
      "stagger_mode": "normal",
      "y_travel_multiplier": 0.58,
      "transform_order": "translate3d(x_px, y_px * y_travel_multiplier, z_px) rotateX(rotate_x_deg) rotateY(rotate_y_deg) rotate(rotate_deg) scale(scale)",
      "fill_behavior": "retain final frame after each phase",
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      },
      "content_replacement": "current phrase is cleared and replaced only after exit_total_ms + micro_delay_ms"
    },
    "renderer": {
      "id": "generic-stagger",
      "params": {}
    }
  },
  {
    "id": "bottom-up-letters",
    "display_name": "Bottom-Up Letters",
    "description": "Letters rise from below in a pronounced staircase, one symbol at a time, with zero blur.",
    "inspiration": "Apple-style keynote typography, sharp lower-thirds, and clean editorial word swaps.",
    "target": "per-character",
    "enter": {
      "duration_ms": 400,
      "stagger_ms": 88,
      "easing": "cubic-bezier(0.18, 1, 0.32, 1)",
      "from": {
        "opacity": 0,
        "y_px": 46
      },
      "to": {
        "opacity": 1,
        "y_px": 0
      }
    },
    "exit": {
      "duration_ms": 280,
      "stagger_ms": 28,
      "easing": "cubic-bezier(0.7, 0, 0.84, 0)",
      "from": {
        "opacity": 1,
        "y_px": 0
      },
      "to": {
        "opacity": 0,
        "y_px": -14
      }
    },
    "samples": [
      "Shift",
      "Stage",
      "Letter"
    ],
    "runtime": {
      "preset": "website-default",
      "speed_multiplier": 0.72,
      "hold_ms": 550,
      "gap_ms": 320,
      "y_travel_multiplier": 0.58,
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      }
    },
    "playback": {
      "kind": "loop",
      "cycle": [
        "enter",
        "hold",
        "exit",
        "micro-delay",
        "gap"
      ],
      "replacement_behavior": "exit-before-enter",
      "hold_ms": 550,
      "micro_delay_ms": 35,
      "gap_ms": 320
    },
    "timing": {
      "enter": {
        "source_duration_ms": 400,
        "source_stagger_ms": 88,
        "scaled_duration_ms": 288,
        "scaled_stagger_ms": 63,
        "easing": "cubic-bezier(0.18, 1, 0.32, 1)"
      },
      "exit": {
        "source_duration_ms": 280,
        "source_stagger_ms": 28,
        "scaled_duration_ms": 202,
        "scaled_stagger_ms": 20,
        "easing": "cubic-bezier(0.7, 0, 0.84, 0)"
      },
      "total_formulas": {
        "enter_total_ms": "enter.scaled_duration_ms + max(0, animated_unit_count - 1) * enter.scaled_stagger_ms",
        "exit_total_ms": "exit.scaled_duration_ms + max(0, animated_unit_count - 1) * exit.scaled_stagger_ms"
      }
    },
    "rendering_contract": {
      "renderer": "generic-stagger",
      "target": "per-character",
      "stagger_mode": "normal",
      "y_travel_multiplier": 0.58,
      "transform_order": "translate3d(x_px, y_px * y_travel_multiplier, z_px) rotateX(rotate_x_deg) rotateY(rotate_y_deg) rotate(rotate_deg) scale(scale)",
      "fill_behavior": "retain final frame after each phase",
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      },
      "content_replacement": "current phrase is cleared and replaced only after exit_total_ms + micro_delay_ms"
    },
    "renderer": {
      "id": "generic-stagger",
      "params": {}
    }
  },
  {
    "id": "top-down-letters",
    "display_name": "Top-Down Letters",
    "description": "Letters descend from above in a pronounced staircase, one symbol at a time, with zero blur.",
    "inspiration": "Apple-style keynote typography, crisp editorial headers, and controlled top-down word reveals.",
    "target": "per-character",
    "enter": {
      "duration_ms": 400,
      "stagger_ms": 88,
      "easing": "cubic-bezier(0.18, 1, 0.32, 1)",
      "from": {
        "opacity": 0,
        "y_px": -46
      },
      "to": {
        "opacity": 1,
        "y_px": 0
      }
    },
    "exit": {
      "duration_ms": 280,
      "stagger_ms": 28,
      "easing": "cubic-bezier(0.7, 0, 0.84, 0)",
      "from": {
        "opacity": 1,
        "y_px": 0
      },
      "to": {
        "opacity": 0,
        "y_px": 14
      }
    },
    "samples": [
      "Signal",
      "Header",
      "Vector"
    ],
    "runtime": {
      "preset": "website-default",
      "speed_multiplier": 0.72,
      "hold_ms": 550,
      "gap_ms": 320,
      "y_travel_multiplier": 0.58,
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      }
    },
    "playback": {
      "kind": "loop",
      "cycle": [
        "enter",
        "hold",
        "exit",
        "micro-delay",
        "gap"
      ],
      "replacement_behavior": "exit-before-enter",
      "hold_ms": 550,
      "micro_delay_ms": 35,
      "gap_ms": 320
    },
    "timing": {
      "enter": {
        "source_duration_ms": 400,
        "source_stagger_ms": 88,
        "scaled_duration_ms": 288,
        "scaled_stagger_ms": 63,
        "easing": "cubic-bezier(0.18, 1, 0.32, 1)"
      },
      "exit": {
        "source_duration_ms": 280,
        "source_stagger_ms": 28,
        "scaled_duration_ms": 202,
        "scaled_stagger_ms": 20,
        "easing": "cubic-bezier(0.7, 0, 0.84, 0)"
      },
      "total_formulas": {
        "enter_total_ms": "enter.scaled_duration_ms + max(0, animated_unit_count - 1) * enter.scaled_stagger_ms",
        "exit_total_ms": "exit.scaled_duration_ms + max(0, animated_unit_count - 1) * exit.scaled_stagger_ms"
      }
    },
    "rendering_contract": {
      "renderer": "generic-stagger",
      "target": "per-character",
      "stagger_mode": "normal",
      "y_travel_multiplier": 0.58,
      "transform_order": "translate3d(x_px, y_px * y_travel_multiplier, z_px) rotateX(rotate_x_deg) rotateY(rotate_y_deg) rotate(rotate_deg) scale(scale)",
      "fill_behavior": "retain final frame after each phase",
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      },
      "content_replacement": "current phrase is cleared and replaced only after exit_total_ms + micro_delay_ms"
    },
    "renderer": {
      "id": "generic-stagger",
      "params": {}
    }
  },
  {
    "id": "kinetic-center-build",
    "display_name": "Kinetic Center Build",
    "description": "A word appears in the center; each new word enters from right to left with a soft blur and pushes the existing line until the full phrase locks centered.",
    "inspiration": "Apple keynote kinetic editorial typography and sequential phrase builds.",
    "target": "per-word",
    "enter": {
      "duration_ms": 360,
      "stagger_ms": 0,
      "easing": "cubic-bezier(0.2, 0.8, 0.2, 1)",
      "from": {
        "opacity": 0,
        "y_px": 6,
        "scale": 0.992,
        "blur_px": 3.5
      },
      "to": {
        "opacity": 1,
        "y_px": 0,
        "scale": 1,
        "blur_px": 0
      }
    },
    "exit": {
      "duration_ms": 260,
      "stagger_ms": 0,
      "easing": "cubic-bezier(0.4, 0, 0.2, 1)",
      "from": {
        "opacity": 1,
        "y_px": 0,
        "blur_px": 0
      },
      "to": {
        "opacity": 0,
        "y_px": -6,
        "blur_px": 2.5
      }
    },
    "samples": [
      "Words push left."
    ],
    "runtime": {
      "preset": "website-default",
      "speed_multiplier": 0.72,
      "hold_ms": 550,
      "gap_ms": 320,
      "y_travel_multiplier": 0.58,
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      }
    },
    "playback": {
      "kind": "loop",
      "cycle": [
        "build-phrase",
        "hold",
        "exit-phrase",
        "gap"
      ],
      "replacement_behavior": "phrase-loop",
      "hold_ms": 706,
      "micro_delay_ms": 0,
      "gap_ms": 158
    },
    "timing": {
      "first_word": {
        "source_duration_ms": 340,
        "scaled_duration_ms": 245,
        "easing": "cubic-bezier(0.2, 0.8, 0.2, 1)"
      },
      "push": {
        "source_duration_ms": 430,
        "scaled_duration_ms": 310,
        "easing": "cubic-bezier(0.2, 0.8, 0.2, 1)"
      },
      "exit": {
        "source_duration_ms": 260,
        "scaled_duration_ms": 187,
        "easing": "cubic-bezier(0.4, 0, 0.2, 1)"
      },
      "hold_ms": 706,
      "gap_ms": 158
    },
    "rendering_contract": {
      "renderer": "kinetic-center-build",
      "target": "per-word",
      "stagger_mode": "normal",
      "coordinate_space": "renderer-pixels",
      "y_travel_multiplier": 1,
      "y_travel_multiplier_note": "runtime.y_travel_multiplier is not applied to kinetic build coordinates; x/y values in build params are final transform pixels.",
      "transform_order": "translate(-50%, -50%) translate3d(x_px, y_px, 0) scale(scale)",
      "fill_behavior": "retain final frame after each phase",
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      },
      "content_replacement": "follow renderer recipe algorithm"
    },
    "renderer": {
      "id": "kinetic-center-build",
      "params": {
        "entry_direction": "from-right",
        "line_alignment": "center",
        "first_word_duration_ms": 340,
        "push_duration_ms": 430,
        "entry_offset_px": 88,
        "word_gap_px": 10,
        "first_word_y_px": 6,
        "entry_scale": 0.992,
        "entry_blur_px": 3.5,
        "reflow_blur_px": 0.8,
        "exit_y_px": -6,
        "exit_blur_px": 2.5,
        "easing": "cubic-bezier(0.2, 0.8, 0.2, 1)",
        "exit_easing": "cubic-bezier(0.4, 0, 0.2, 1)",
        "phrase_samples": [
          [
            "Words",
            "push",
            "left"
          ],
          [
            "Type",
            "locks",
            "center"
          ],
          [
            "Build",
            "the",
            "line"
          ]
        ]
      }
    }
  },
  {
    "id": "short-slide-right",
    "display_name": "Short Slide Right",
    "description": "The whole phrase glides in from the left as one compact move, while the words themselves are revealed in sequence only through opacity.",
    "inspiration": "Keynote-style editorial headings where motion is present but tightly restrained.",
    "target": "per-word",
    "enter": {
      "duration_ms": 520,
      "stagger_ms": 92,
      "easing": "cubic-bezier(0.2, 0.8, 0.2, 1)",
      "from": {
        "opacity": 1,
        "x_px": -24,
        "blur_px": 1.2
      },
      "to": {
        "opacity": 1,
        "x_px": 0,
        "blur_px": 0
      }
    },
    "exit": {
      "duration_ms": 320,
      "stagger_ms": 0,
      "easing": "cubic-bezier(0.4, 0, 0.2, 1)",
      "from": {
        "opacity": 1,
        "x_px": 0,
        "blur_px": 0
      },
      "to": {
        "opacity": 0,
        "x_px": 12,
        "blur_px": 1
      }
    },
    "samples": [
      "Move with intent.",
      "Words glide across.",
      "Build the rhythm."
    ],
    "runtime": {
      "preset": "website-default",
      "speed_multiplier": 0.72,
      "hold_ms": 550,
      "gap_ms": 320,
      "y_travel_multiplier": 0.58,
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      }
    },
    "playback": {
      "kind": "loop",
      "cycle": [
        "enter",
        "hold",
        "exit",
        "gap"
      ],
      "replacement_behavior": "exit-before-enter",
      "hold_ms": 550,
      "micro_delay_ms": 0,
      "gap_ms": 320
    },
    "timing": {
      "enter_title": {
        "source_duration_ms": 520,
        "source_stagger_ms": 92,
        "scaled_duration_ms": 374,
        "scaled_stagger_ms": 66,
        "easing": "cubic-bezier(0.2, 0.8, 0.2, 1)"
      },
      "enter_word_opacity": {
        "source_duration_ms": 210,
        "scaled_duration_ms": 151,
        "delay_step_ms": 66,
        "easing": "cubic-bezier(0.2, 0.8, 0.2, 1)"
      },
      "exit_title": {
        "source_duration_ms": 320,
        "source_stagger_ms": 0,
        "scaled_duration_ms": 230,
        "scaled_stagger_ms": 0,
        "easing": "cubic-bezier(0.4, 0, 0.2, 1)"
      },
      "total_formulas": {
        "enter_total_ms": "enter_title.scaled_duration_ms",
        "exit_total_ms": "exit_title.scaled_duration_ms"
      }
    },
    "rendering_contract": {
      "renderer": "shared-slide-opacity-stage",
      "target": "per-word",
      "stagger_mode": "normal",
      "y_travel_multiplier": 0.58,
      "transform_order": "translate3d(x_px, y_px * y_travel_multiplier, z_px) rotateX(rotate_x_deg) rotateY(rotate_y_deg) rotate(rotate_deg) scale(scale)",
      "fill_behavior": "retain final frame after each phase",
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      },
      "content_replacement": "follow renderer recipe algorithm"
    },
    "renderer": {
      "id": "shared-slide-opacity-stage",
      "params": {
        "word_opacity_duration_ms": 210,
        "word_opacity_from": 0,
        "word_opacity_to": 1
      }
    }
  },
  {
    "id": "short-slide-down",
    "display_name": "Short Slide Down",
    "description": "Each new word drops in from above into its own line and pushes the existing stack downward until a centered three-line composition locks in place.",
    "inspiration": "Keynote-style editorial headings where motion is present but tightly restrained.",
    "target": "per-word",
    "enter": {
      "duration_ms": 520,
      "stagger_ms": 0,
      "easing": "cubic-bezier(0.2, 0.8, 0.2, 1)",
      "from": {
        "opacity": 0,
        "y_px": -24,
        "blur_px": 2.4,
        "scale": 0.992
      },
      "to": {
        "opacity": 1,
        "y_px": 0,
        "blur_px": 0,
        "scale": 1
      }
    },
    "exit": {
      "duration_ms": 320,
      "stagger_ms": 0,
      "easing": "cubic-bezier(0.4, 0, 0.2, 1)",
      "from": {
        "opacity": 1,
        "y_px": 0,
        "blur_px": 0,
        "scale": 1
      },
      "to": {
        "opacity": 0,
        "y_px": 10,
        "blur_px": 1.2,
        "scale": 1
      }
    },
    "samples": [
      "Build from above."
    ],
    "runtime": {
      "preset": "website-default",
      "speed_multiplier": 0.72,
      "hold_ms": 550,
      "gap_ms": 320,
      "y_travel_multiplier": 0.58,
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      }
    },
    "playback": {
      "kind": "loop",
      "cycle": [
        "build-phrase",
        "hold",
        "exit-phrase",
        "gap"
      ],
      "replacement_behavior": "phrase-loop",
      "hold_ms": 792,
      "micro_delay_ms": 0,
      "gap_ms": 130
    },
    "timing": {
      "first_word": {
        "source_duration_ms": 360,
        "scaled_duration_ms": 259,
        "easing": "cubic-bezier(0.2, 0.8, 0.2, 1)"
      },
      "push": {
        "source_duration_ms": 500,
        "scaled_duration_ms": 360,
        "easing": "cubic-bezier(0.2, 0.8, 0.2, 1)"
      },
      "exit": {
        "source_duration_ms": 320,
        "scaled_duration_ms": 230,
        "easing": "cubic-bezier(0.4, 0, 0.2, 1)"
      },
      "hold_ms": 792,
      "gap_ms": 130
    },
    "rendering_contract": {
      "renderer": "kinetic-top-build",
      "target": "per-word",
      "stagger_mode": "normal",
      "coordinate_space": "renderer-pixels",
      "y_travel_multiplier": 1,
      "y_travel_multiplier_note": "runtime.y_travel_multiplier is not applied to kinetic build coordinates; x/y values in build params are final transform pixels.",
      "transform_order": "translate(-50%, -50%) translate3d(0, y_px, 0) scale(scale)",
      "fill_behavior": "retain final frame after each phase",
      "initial_delay_ms": {
        "mode": "random-range",
        "min": 0,
        "max": 400
      },
      "content_replacement": "follow renderer recipe algorithm"
    },
    "renderer": {
      "id": "kinetic-top-build",
      "params": {
        "first_word_duration_ms": 360,
        "push_duration_ms": 500,
        "exit_duration_ms": 320,
        "hold_ms": 1100,
        "between_phrases_ms": 180,
        "entry_offset_y_px": -28,
        "line_gap_px": 12,
        "first_word_y_px": -14,
        "entry_scale": 0.992,
        "entry_blur_px": 2.4,
        "reflow_blur_px": 0.7,
        "exit_y_px": 10,
        "exit_blur_px": 1.2,
        "easing": "cubic-bezier(0.2, 0.8, 0.2, 1)",
        "exit_easing": "cubic-bezier(0.4, 0, 0.2, 1)"
      }
    }
  }
];
